#pragma once

// Change only DIAG_STAGE for the normal diagnostic progression. Make can also
// override it with: make DIAG_STAGE=DIAG_STAGE_CONTROLS_INIT
#define DIAG_STAGE_MINIMAL_BYPASS 0
#define DIAG_STAGE_MAILBOX_OBJECT 1
#define DIAG_STAGE_CONTROLS_OBJECT 2
#define DIAG_STAGE_CONTROLS_INIT 3
#define DIAG_STAGE_CONTROLS_SERVICE 4
#define DIAG_STAGE_TELEMETRY_OBJECT 5
#define DIAG_STAGE_TELEMETRY_INIT 6
#define DIAG_STAGE_TELEMETRY_TRAFFIC 7
#define DIAG_STAGE_TUNER_OBJECTS 8
#define DIAG_STAGE_TUNER_INIT 9
#define DIAG_STAGE_TUNER_CAPTURE 10
#define DIAG_STAGE_TUNER_ANALYSIS 11
#define DIAG_STAGE_THERMAL_OBJECT 12
#define DIAG_STAGE_THERMAL_INIT 13
#define DIAG_STAGE_THERMAL_SERVICE 14
#define DIAG_STAGE_AUDIOENGINE_OBJECT 15
#define DIAG_STAGE_AUDIOENGINE_INIT 16

#define DIAG_STAGE_AUDIOENGINE_PROCESS_DRY 170
#define DIAG_STAGE_AUDIOENGINE_PROCESS_MAILBOX 171
#define DIAG_STAGE_AUDIOENGINE_PROCESS_TUNER 172
#define DIAG_STAGE_AUDIOENGINE_PROCESS_TRANSITION 173
#define DIAG_STAGE_AUDIOENGINE_PROCESS_THERMAL 174
#define DIAG_STAGE_AUDIOENGINE_PROCESS_DISPATCH 175

#define DIAG_STAGE_FX_CHORUS 180
#define DIAG_STAGE_FX_REVERB 181
#define DIAG_STAGE_FX_CRUSHER 182
#define DIAG_STAGE_FX_GRANULAR 183
#define DIAG_STAGE_PRODUCTION 1000

#ifndef DIAG_STAGE
#define DIAG_STAGE DIAG_STAGE_MINIMAL_BYPASS
#endif

#if DIAG_STAGE == DIAG_STAGE_MINIMAL_BYPASS
#define DIAG_STAGE_LABEL "MINIMAL_BYPASS"
#elif DIAG_STAGE == DIAG_STAGE_MAILBOX_OBJECT
#define DIAG_STAGE_LABEL "MAILBOX_OBJECT"
#elif DIAG_STAGE == DIAG_STAGE_CONTROLS_OBJECT
#define DIAG_STAGE_LABEL "CONTROLS_OBJECT"
#elif DIAG_STAGE == DIAG_STAGE_CONTROLS_INIT
#define DIAG_STAGE_LABEL "CONTROLS_INIT"
#elif DIAG_STAGE == DIAG_STAGE_CONTROLS_SERVICE
#define DIAG_STAGE_LABEL "CONTROLS_SERVICE"
#elif DIAG_STAGE == DIAG_STAGE_TELEMETRY_OBJECT
#define DIAG_STAGE_LABEL "TELEMETRY_OBJECT"
#elif DIAG_STAGE == DIAG_STAGE_TELEMETRY_INIT
#define DIAG_STAGE_LABEL "TELEMETRY_INIT"
#elif DIAG_STAGE == DIAG_STAGE_TELEMETRY_TRAFFIC
#define DIAG_STAGE_LABEL "TELEMETRY_TRAFFIC"
#elif DIAG_STAGE == DIAG_STAGE_TUNER_OBJECTS
#define DIAG_STAGE_LABEL "TUNER_OBJECTS"
#elif DIAG_STAGE == DIAG_STAGE_TUNER_INIT
#define DIAG_STAGE_LABEL "TUNER_INIT"
#elif DIAG_STAGE == DIAG_STAGE_TUNER_CAPTURE
#define DIAG_STAGE_LABEL "TUNER_CAPTURE"
#elif DIAG_STAGE == DIAG_STAGE_TUNER_ANALYSIS
#define DIAG_STAGE_LABEL "TUNER_ANALYSIS"
#elif DIAG_STAGE == DIAG_STAGE_THERMAL_OBJECT
#define DIAG_STAGE_LABEL "THERMAL_OBJECT"
#elif DIAG_STAGE == DIAG_STAGE_THERMAL_INIT
#define DIAG_STAGE_LABEL "THERMAL_INIT"
#elif DIAG_STAGE == DIAG_STAGE_THERMAL_SERVICE
#define DIAG_STAGE_LABEL "THERMAL_SERVICE"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_OBJECT
#define DIAG_STAGE_LABEL "AUDIOENGINE_OBJECT"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_INIT
#define DIAG_STAGE_LABEL "AUDIOENGINE_INIT"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_DRY
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_DRY"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_MAILBOX
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_MAILBOX"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_TUNER
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_TUNER"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_TRANSITION
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_TRANSITION"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_THERMAL
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_THERMAL"
#elif DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_DISPATCH
#define DIAG_STAGE_LABEL "AUDIOENGINE_PROCESS_DISPATCH"
#elif DIAG_STAGE == DIAG_STAGE_FX_CHORUS
#define DIAG_STAGE_LABEL "FX_CHORUS"
#elif DIAG_STAGE == DIAG_STAGE_FX_REVERB
#define DIAG_STAGE_LABEL "FX_REVERB"
#elif DIAG_STAGE == DIAG_STAGE_FX_CRUSHER
#define DIAG_STAGE_LABEL "FX_CRUSHER"
#elif DIAG_STAGE == DIAG_STAGE_FX_GRANULAR
#define DIAG_STAGE_LABEL "FX_GRANULAR"
#elif DIAG_STAGE == DIAG_STAGE_PRODUCTION
#define DIAG_STAGE_LABEL "PRODUCTION"
#else
#error "Unknown DIAG_STAGE value"
#endif

#define DIAG_AUDIO_DIRECT_STEREO_BYPASS 0
#define DIAG_AUDIO_DIRECT_MONO_BYPASS 1
#define DIAG_AUDIO_SINE_440 2
#define DIAG_AUDIO_SILENCE 3
#define DIAG_AUDIO_ENGINE 4

#define DIAG_HAS_MAILBOX (DIAG_STAGE >= DIAG_STAGE_MAILBOX_OBJECT)
#define DIAG_HAS_CONTROLS (DIAG_STAGE >= DIAG_STAGE_CONTROLS_OBJECT)
#define DIAG_INIT_CONTROLS (DIAG_STAGE >= DIAG_STAGE_CONTROLS_INIT)
#define DIAG_SERVICE_CONTROLS (DIAG_STAGE >= DIAG_STAGE_CONTROLS_SERVICE)
#define DIAG_HAS_TELEMETRY (DIAG_STAGE >= DIAG_STAGE_TELEMETRY_OBJECT)
#define DIAG_INIT_TELEMETRY (DIAG_STAGE >= DIAG_STAGE_TELEMETRY_INIT)
#define DIAG_SEND_TELEMETRY (DIAG_STAGE >= DIAG_STAGE_TELEMETRY_TRAFFIC)
#define DIAG_HAS_TUNER_OBJECTS (DIAG_STAGE >= DIAG_STAGE_TUNER_OBJECTS)
#define DIAG_INIT_TUNER (DIAG_STAGE >= DIAG_STAGE_TUNER_INIT)
#define DIAG_CAPTURE_TUNER (DIAG_STAGE >= DIAG_STAGE_TUNER_CAPTURE)
#define DIAG_ANALYZE_TUNER (DIAG_STAGE >= DIAG_STAGE_TUNER_ANALYSIS)
#define DIAG_HAS_THERMAL (DIAG_STAGE >= DIAG_STAGE_THERMAL_OBJECT)
#define DIAG_INIT_THERMAL (DIAG_STAGE >= DIAG_STAGE_THERMAL_INIT)
#define DIAG_SERVICE_THERMAL (DIAG_STAGE >= DIAG_STAGE_THERMAL_SERVICE)
#define DIAG_HAS_AUDIOENGINE (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_OBJECT)
#define DIAG_INIT_AUDIOENGINE (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_INIT)
#define DIAG_PROCESS_AUDIOENGINE \
    (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_PROCESS_DRY)

#define DIAG_ENGINE_USE_MAILBOX \
    (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_PROCESS_MAILBOX)
#define DIAG_ENGINE_CAPTURE_TUNER \
    (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_PROCESS_TUNER)
#define DIAG_ENGINE_TRANSITIONS \
    (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_PROCESS_TRANSITION)
#define DIAG_ENGINE_DISPATCH \
    (DIAG_STAGE >= DIAG_STAGE_AUDIOENGINE_PROCESS_DISPATCH)
#define DIAG_ENGINE_PROCESS_FX                 \
    ((DIAG_STAGE >= DIAG_STAGE_FX_CHORUS       \
      && DIAG_STAGE <= DIAG_STAGE_FX_GRANULAR) \
     || DIAG_STAGE == DIAG_STAGE_PRODUCTION)

// Thermal monitoring remains active in later diagnostic stages, but only the
// dedicated Stage 174 test and production publish/enforce audio shutdown.
#ifndef DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN
#define DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN               \
    (DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_THERMAL \
     || DIAG_STAGE == DIAG_STAGE_PRODUCTION)
#endif

#ifndef DIAG_AUDIO_MODE
#if DIAG_PROCESS_AUDIOENGINE
#define DIAG_AUDIO_MODE DIAG_AUDIO_ENGINE
#else
#define DIAG_AUDIO_MODE DIAG_AUDIO_DIRECT_STEREO_BYPASS
#endif
#endif

// Optional object-construction overrides. Diagnostic effect profiles default to
// exactly one concrete effect; production requires all four.
#ifndef DIAG_FX_CHORUS
#define DIAG_FX_CHORUS \
    (DIAG_STAGE == DIAG_STAGE_FX_CHORUS || DIAG_STAGE == DIAG_STAGE_PRODUCTION)
#endif
#ifndef DIAG_FX_REVERB
#define DIAG_FX_REVERB \
    (DIAG_STAGE == DIAG_STAGE_FX_REVERB || DIAG_STAGE == DIAG_STAGE_PRODUCTION)
#endif
#ifndef DIAG_FX_CRUSHER
#define DIAG_FX_CRUSHER \
    (DIAG_STAGE == DIAG_STAGE_FX_CRUSHER || DIAG_STAGE == DIAG_STAGE_PRODUCTION)
#endif
#ifndef DIAG_FX_GRANULAR
#define DIAG_FX_GRANULAR                  \
    (DIAG_STAGE == DIAG_STAGE_FX_GRANULAR \
     || DIAG_STAGE == DIAG_STAGE_PRODUCTION)
#endif

#define DIAG_FORCE_EFFECT_NONE 0
#define DIAG_FORCE_EFFECT_CHORUS 1
#define DIAG_FORCE_EFFECT_REVERB 2
#define DIAG_FORCE_EFFECT_CRUSHER 3
#define DIAG_FORCE_EFFECT_GRANULAR 4

#ifndef DIAG_FORCE_EFFECT
#if DIAG_STAGE == DIAG_STAGE_FX_CHORUS
#define DIAG_FORCE_EFFECT DIAG_FORCE_EFFECT_CHORUS
#elif DIAG_STAGE == DIAG_STAGE_FX_REVERB
#define DIAG_FORCE_EFFECT DIAG_FORCE_EFFECT_REVERB
#elif DIAG_STAGE == DIAG_STAGE_FX_CRUSHER
#define DIAG_FORCE_EFFECT DIAG_FORCE_EFFECT_CRUSHER
#elif DIAG_STAGE == DIAG_STAGE_FX_GRANULAR
#define DIAG_FORCE_EFFECT DIAG_FORCE_EFFECT_GRANULAR
#else
#define DIAG_FORCE_EFFECT DIAG_FORCE_EFFECT_NONE
#endif
#endif

#if DIAG_AUDIO_MODE < DIAG_AUDIO_DIRECT_STEREO_BYPASS \
    || DIAG_AUDIO_MODE > DIAG_AUDIO_ENGINE
#error "Invalid DIAG_AUDIO_MODE"
#endif
#if DIAG_AUDIO_MODE == DIAG_AUDIO_ENGINE && !DIAG_PROCESS_AUDIOENGINE
#error "DIAG_AUDIO_ENGINE requires an AudioEngine process stage"
#endif
#if DIAG_PROCESS_AUDIOENGINE && DIAG_AUDIO_MODE != DIAG_AUDIO_ENGINE
#error "AudioEngine process stages require DIAG_AUDIO_ENGINE"
#endif
#if DIAG_STAGE == DIAG_STAGE_PRODUCTION                        \
    && (!DIAG_FX_CHORUS || !DIAG_FX_REVERB || !DIAG_FX_CRUSHER \
        || !DIAG_FX_GRANULAR)
#error "Production requires all effects"
#endif
#if(DIAG_FX_CHORUS || DIAG_FX_REVERB || DIAG_FX_CRUSHER || DIAG_FX_GRANULAR) \
    && !DIAG_HAS_AUDIOENGINE
#error "Effect objects require an AudioEngine construction stage"
#endif
#if DIAG_FORCE_EFFECT < DIAG_FORCE_EFFECT_NONE \
    || DIAG_FORCE_EFFECT > DIAG_FORCE_EFFECT_GRANULAR
#error "Invalid DIAG_FORCE_EFFECT"
#endif
#if DIAG_ENGINE_PROCESS_FX && DIAG_FORCE_EFFECT == DIAG_FORCE_EFFECT_CHORUS \
    && !DIAG_FX_CHORUS
#error "Forced chorus requires DIAG_FX_CHORUS"
#endif
#if DIAG_ENGINE_PROCESS_FX && DIAG_FORCE_EFFECT == DIAG_FORCE_EFFECT_REVERB \
    && !DIAG_FX_REVERB
#error "Forced reverb requires DIAG_FX_REVERB"
#endif
#if DIAG_ENGINE_PROCESS_FX && DIAG_FORCE_EFFECT == DIAG_FORCE_EFFECT_CRUSHER \
    && !DIAG_FX_CRUSHER
#error "Forced crusher requires DIAG_FX_CRUSHER"
#endif
#if DIAG_ENGINE_PROCESS_FX && DIAG_FORCE_EFFECT == DIAG_FORCE_EFFECT_GRANULAR \
    && !DIAG_FX_GRANULAR
#error "Forced granular requires DIAG_FX_GRANULAR"
#endif
#if DIAG_ENGINE_PROCESS_FX && DIAG_STAGE != DIAG_STAGE_PRODUCTION \
    && DIAG_FORCE_EFFECT == DIAG_FORCE_EFFECT_NONE
#error "A diagnostic effect-processing profile must force one effect"
#endif
#if !DIAG_ENGINE_PROCESS_FX && DIAG_FORCE_EFFECT != DIAG_FORCE_EFFECT_NONE
#error "DIAG_FORCE_EFFECT is only valid in an effect-processing profile"
#endif
#if DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN && !DIAG_ENGINE_USE_MAILBOX
#error "Thermal audio enforcement requires the AudioEngine mailbox path"
#endif
#if DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN && !DIAG_SERVICE_THERMAL
#error "Thermal audio enforcement requires ThermalMonitor service"
#endif
#if(DIAG_STAGE == DIAG_STAGE_AUDIOENGINE_PROCESS_THERMAL \
    || DIAG_STAGE == DIAG_STAGE_PRODUCTION)              \
    && !DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN
#error "Stage 174 and production require thermal audio enforcement"
#endif

#define DIAG_STRINGIFY_INNER(x) #x
#define DIAG_STRINGIFY(x) DIAG_STRINGIFY_INNER(x)
#if DIAG_FX_CHORUS
#define DIAG_FX_CHORUS_LABEL "1"
#else
#define DIAG_FX_CHORUS_LABEL "0"
#endif
#if DIAG_FX_REVERB
#define DIAG_FX_REVERB_LABEL "1"
#else
#define DIAG_FX_REVERB_LABEL "0"
#endif
#if DIAG_FX_CRUSHER
#define DIAG_FX_CRUSHER_LABEL "1"
#else
#define DIAG_FX_CRUSHER_LABEL "0"
#endif
#if DIAG_FX_GRANULAR
#define DIAG_FX_GRANULAR_LABEL "1"
#else
#define DIAG_FX_GRANULAR_LABEL "0"
#endif
#if DIAG_ENFORCE_THERMAL_AUDIO_SHUTDOWN
#define DIAG_THERMAL_AUDIO_LABEL "1"
#else
#define DIAG_THERMAL_AUDIO_LABEL "0"
#endif
#pragma message("DIAG_STAGE=" DIAG_STRINGIFY(DIAG_STAGE) " " DIAG_STAGE_LABEL)
#pragma message("DIAG_AUDIO_MODE=" DIAG_STRINGIFY(DIAG_AUDIO_MODE) ", FX[C,R,X,G]=" DIAG_FX_CHORUS_LABEL "," DIAG_FX_REVERB_LABEL "," DIAG_FX_CRUSHER_LABEL "," DIAG_FX_GRANULAR_LABEL ", FORCE=" DIAG_STRINGIFY(DIAG_FORCE_EFFECT) ", THERMAL_AUDIO=" DIAG_THERMAL_AUDIO_LABEL)
